#!/usr/bin/env python3
"""Parse the NZ slang CSV into an embedded JS data file for the quiz app.

Usage:
    python3 scripts/build-data.py

Reads the CSV in the repo root and writes docs/data.js as
`window.SLANG_DATA = [...]`. Embedding as JS (rather than a fetched JSON
file) means the app also works when opened directly from disk.
"""
import csv
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_PATH = os.path.join(ROOT, "NZ YOUTH SLANG  (Clean) - Sheet1.csv")
OUT_PATH = os.path.join(ROOT, "docs", "data.js")

# Column indices in the source sheet.
TERM, CATEGORY, MEANING, EXAMPLE = 3, 4, 5, 6


def clean(s):
    return " ".join((s or "").split()).strip()


def main():
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        rows = list(csv.reader(f))

    seen = set()
    entries = []
    for r in rows[1:]:
        if len(r) <= EXAMPLE:
            continue
        term = clean(r[TERM])
        meaning = clean(r[MEANING])
        category = clean(r[CATEGORY])
        example = clean(r[EXAMPLE])
        # Require a real term + meaning; skip the note rows at the top.
        if not term or not meaning or not category:
            continue
        # A numeric "Numb #" marks genuine entries; note rows lack it.
        if not clean(r[1]).isdigit():
            continue
        key = term.lower()
        if key in seen:
            continue
        seen.add(key)
        entries.append(
            {
                "term": term,
                "category": category,
                "meaning": meaning,
                "example": example,
            }
        )

    entries.sort(key=lambda e: e["term"].lower())
    payload = json.dumps(entries, ensure_ascii=False, indent=0)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build-data.py — do not edit by hand.\n")
        f.write("window.SLANG_DATA = ")
        f.write(payload)
        f.write(";\n")

    print(f"Wrote {len(entries)} terms to {OUT_PATH}")
    cats = {}
    for e in entries:
        cats[e["category"]] = cats.get(e["category"], 0) + 1
    for c, n in sorted(cats.items(), key=lambda x: -x[1]):
        print(f"  {c}: {n}")


if __name__ == "__main__":
    main()
